### PR TITLE
[issue 144] - Support Red Hat Build of Keycloak (new productised version of Keycloak)

### LINKED ISSUE #144: Enable support for Red Hat Build of Keycloak (RHBK) via Keycloak provisioning tooling, and deprecate support for RHSSO 7.6 provisioning
**Is your feature request related to a problem? Please describe.**
Intersmash must support Red Hat Build of Keycloak (RHBK) via Keycloak provisioning tooling, and deprecate support for RHSSO 7.6 provisioning.

**Describe the solution you'd like**
- Check that the keycloak provisioning tooling works with RHBK OpenShift deliverables, and fix anything if needed
- Deprecate RHSSO 7.6 provisioning tooling and evaluate impact on internal tests that will have to be modified in order to use the new provisioning tooling 
- Update documentation, specifically mentioning the fact that identifiers (e.g.: class names) are named after their community service (e.g.: KeycloakOperatorProvisioner) and should support the latest product counterpart (e.g.: RHBK) by default.

**Describe alternatives you've considered**
None, Intersmash must support testing with the latest Keycloak product counterpart.

**Additional context**
The deprecation must leave time for internal tests to be modified in order to use the new provisioning tooling

### PR DESCRIPTION
**Pull request by fabiobrz**
## Description
Make the Intersmash provisioning tooling for Keycloak support  its latest product counterpart too, i.e. Red Hat Build of keycloak (RHBK)

Fix #144 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - [x] I have implemented unit tests to cover my changes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by fabiobrz** [comment]
Adding this comment to track the two verification jobs:

- community: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/Intersmash_intersmash/155/pull-ci-Intersmash-intersmash-main-intersmash-e2e/1773713177402413056

- prod: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/Intersmash_intersmash/155/pull-ci-Intersmash-intersmash-main-prod-intersmash-e2e-prod/1773713177444356096

before removing the last [commit](https://github.com/Intersmash/intersmash/pull/155/commits/3206f0e4fae0256ef8b86365a35c2a41abcbd26a) (SHA is 3206f0e4fae0256ef8b86365a35c2a41abcbd26a of rfuture reference) which is provided by https://github.com/Intersmash/intersmash/pull/162 instead.

As the above mentioned jobs are green, the changes are now ready to be reviewed.

**Comment by marekkopecky** [comment]
LGTM, merging, thank you!

**Pull request merged**
