### PR TITLE
[issue 159] - Freezing supported versions in Intersmash 0.0.2 release

### LINKED ISSUE #159: Freeze supported community and product runtime version defaults for Intersmash 0.0.2 release
The defaults values for community and product runtime version defaults must be updated in order to let Intersmash 0.0.2 build and execute tests with latest GA artifacts and deliverables. 

---
* Environment: N/A
* Steps to reproduce: `mvn clean install -Dmaven.repo.local=./local-repo-community`

### PR DESCRIPTION
**Pull request by fabiobrz**
## Description

Fix #159 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [ ] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - **N/A** - I have implemented unit tests to cover my changes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by marekkopecky** [comment]
@fabiobrz Code changes LGTM, but one CI job failed. Can you please double-check?

**Comment by fabiobrz** [comment]
> @fabiobrz Code changes LGTM, but one CI job failed. Can you please double-check?

Thanks @marekkopecky - those failures are tracked separately by #168 and addressed by #171

**Comment by marekkopecky** [comment]
Thank you! Merging.

**Pull request merged**
