### PR TITLE
[issue 190] - Fix InfinispanOperatorProvisionerTest in order not to use .spec.service.type=cache and .spec.autoscale

### LINKED ISSUE #190: Some InfinispanOperatorProvisionerTest tests fail when run with community settings
Intersmash testsuite execution fails two Infinispan related tests when run with community settings.

**To Reproduce**
`mvn clean install -DskipTests ; mvn test -pl testsuite -Dtest=InfinispanOperatorProvisionerTest`:

```
...
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://api.imash416-5i2e.eapqe.psi.redhat.com:6443/apis/infinispan.org/v1/namespaces/appsint-diil/infinispans. Message: admission webhook "vinfinispan.kb.io" denied the request: Infinispan.infinispan.org "example-infinispan" is invalid: spec.service.type: Forbidden: CacheService is no longer supported.. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.service.type, message=Forbidden: CacheService is no longer supported., reason=FieldValueForbidden, additionalProperties={})], group=infinispan.org, kind=Infinispan, name=example-infinispan, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=admission webhook "vinfinispan.kb.io" denied the request: Infinispan.infinispan.org "example-infinispan" is invalid: spec.service.type: Forbidden: CacheService is no longer supported., metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at org.jboss.intersmash.testsuite.provision.openshift.InfinispanOperatorProvisionerTest.createAndVerifyInfinispan(InfinispanOperatorProvisionerTest.java:297)
```

**Expected behavior**
All the tests should pass.

**Additional context**
This is due to the fact that the community operator is shipping a new release - i.e. - which doesn't support `.spec.service.type=cache`, see https://infinispan.org/docs/infinispan-operator/main/operator.html#services_services
This issue should be fixed by changing the test code in order not to set `.spec.service.type=cache` in any cases, and use `.spec.service.type=datagrid` instead. Another issue should then track the effort to update the Intersmash provisioning tooling for Infinispan provisioning to the latest version, and check whether this would work with against product bits.

### PR DESCRIPTION
**Pull request by fabiobrz**
## Description
Removing a test which specifically sets `.spec.service.type=cache` and changing another one in order to set `.spec.service.type=datagrid`

Fixes #190

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - [x] I have implemented unit tests to cover my changes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by fabiobrz** [comment]
Intersmash PR CI check results
---
Hi @fabiobrz, this comment is meant to report the outcome of Intersmash integration tests,
which were triggered by @fabiobrz comment, see https://github.com/Intersmash/intersmash/pull/191#issuecomment-2322844527.

CI checks job <*continuous-testing-umb-listener-for-intersmash-pr-checks#80*> **FAILED**:


- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-community#34*> reported failures.
Please verify your changes locally or reach out to maintainers in order to investigate the issues.

- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-products-jboss-eap#46*> reported failures.
Please verify your changes locally or reach out to maintainers in order to investigate the issues.

- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-products-jboss-eap-xp#50*> reported failures.
Please verify your changes locally or reach out to maintainers in order to investigate the issues.

**Comment by fabiobrz** [comment]
> ## Intersmash PR CI check results
> 
> Hi @fabiobrz, this comment is meant to report the outcome of Intersmash integration tests, which were triggered by @fabiobrz comment, see [#191 (comment)](https://github.com/Intersmash/intersmash/pull/191#issuecomment-2322844527).
> 
> CI checks job <_continuous-testing-umb-listener-for-intersmash-pr-checks#80_> **FAILED**:
> 
>     * Intersmash integration tests job <_eap-8.x-intersmash-integration-tests-community#34_> reported failures.
>       Please verify your changes locally or reach out to maintainers in order to investigate the issues.
<_eap-8.x-intersmash-integration-tests-community#34_> reported 1 failure, i.e.:
- org.jboss.intersmash.testsuite.provision.openshift.KafkaOperatorProvisionerTest.basicProvisioningTest which is confirmed as an issue by the following run <_eap-8.x-intersmash-integration-tests-community#34_>. Tis is unrelated to the changes in this PR, and tracked separately by #193 :white_check_mark: 

>     * Intersmash integration tests job <_eap-8.x-intersmash-integration-tests-products-jboss-eap#46_> reported failures.
>       Please verify your changes locally or reach out to maintainers in order to investigate the issues.
<_eap-8.x-intersmash-integration-tests-products-jboss-eap#46_> reported 1 failure, i.e.:
- org.jboss.intersmash.testsuite.provision.auto.AutoProvisioningTests.testAppIsLive 
which is intermittent as fixed in <_eap-8.x-intersmash-integration-tests-products-jboss-eap#46_> :heavy_check_mark: 

>     * Intersmash integration tests job <_eap-8.x-intersmash-integration-tests-products-jboss-eap-xp#50_> reported failures.
>       Please verify your changes locally or reach out to maintainers in order to investigate the issues.
<_eap-8.x-intersmash-integration-tests-products-jboss-eap-xp#50_> Reported 2 failures, i.e.:
- org.jboss.intersmash.testsuite.provision.openshift.InfinispanOperatorProvisionerTest.testMinimalTwoReplicasInfinispan
- org.jboss.intersmash.testsuite.provision.openshift.ProvisionerCleanupTestCase.testProvisioningWorkflowCleanup(OpenShiftProvisioner)[1]
Both are intermittent as the latter was fixed in <_eap-8.x-intersmash-integration-tests-products-jboss-eap-xp#52_> and the former in <_eap-8.x-intersmash-integration-tests-products-jboss-eap-xp#52_> :heavy_check_mark: 

Based on the above findings, the changes in the PR are deemed to pass the integration tests and can now be reviewed.

**Comment by marekkopecky** [comment]
> Removing a test which specifically sets .spec.service.type=cache and changing another one in order to set .spec.service.type=datagrid

It seems that this PR doesn't chage any test in order to set .spec.service.type=datagrid. It seems that this PR just removes two tests.

Do you have some tracker for the last part of https://github.com/Intersmash/intersmash/issues/190 ? 

> Another issue should then track the effort to update the Intersmash provisioning tooling for Infinispan provisioning to the latest version, and check whether this would work with against product bits.

Generally I'm not sure whether this is upstream related only, or whether [this](https://infinispan.org/docs/infinispan-operator/main/operator.html#services_services) is related with product as well.

**Comment by fabiobrz** [comment]
> > Removing a test which specifically sets .spec.service.type=cache and changing another one in order to set .spec.service.type=datagrid
> 
> It seems that this PR doesn't chage any test in order to set .spec.service.type=datagrid. It seems that this PR just removes two tests. Can you please double-check this?

Correct, `testMinimalTwoReplicasCacheServiceInfinispan` is removed because it duplicates `testMinimalTwoReplicasInfinispan`, with the only difference that it uses a `.spec.service.type=cache`, which is no longer supported in latest Infinispan, see https://infinispan.org/docs/infinispan-operator/main/operator.html#services_services
Then, once that was removed I stumbled upon a different failure, mentioning `.spec.autoscale` being no longer supported by the operator, so I had to remove the `testMinimalCacheServiceInfinispanWithAutoscale` test too. Sadly, it seem they didn't document the deprecation. The only note is here:
- https://github.com/infinispan/infinispan-operator/blob/2.4.3.Final/config/crd/bases/infinispan.org_infinispans.yaml#L888-L889
and it wrongly states that "it has no longer effect" since Infinispan 15.z. Instead it actually results in an error from the Operator runtime:
```
[ERROR] org.jboss.intersmash.testsuite.provision.openshift.InfinispanOperatorProvisionerTest.testMinimalCacheServiceInfinispanWithAutoscale  Time elapsed: 30.861 s  <<< ERROR!
...
admission webhook "vinfinispan.kb.io" denied the request: Infinispan.infinispan.org "example-infinispan" is invalid: spec.autoscale: Forbidden: Autoscale is no longer supported. Please remove spec.autoscale field.. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.autoscale, message=Forbidden: Autoscale is no longer supported. Please remove spec.autoscale field., reason=FieldValueForbidden, additionalProperties={})], group=infinispan.org, kind=Infinispan, name=example-infinispan, retryAfterSeconds=null,
 ...        
        at org.jboss.intersmash.testsuite.provision.openshift.InfinispanOperatorProvisionerTest.createAndVerifyInfinispan(InfinispanOperatorProvisionerTest.java:243)
        at org.jboss.intersmash.testsuite.provision.openshift.InfinispanOperatorProvisionerTest.verifyMinimalCacheServiceInfinispanWithAutoscale(InfinispanOperatorProvisionerTest.java:399)
        at org.jboss.intersmash.testsuite.provision.openshift.InfinispanOperatorProvisionerTest.testMinimalCacheServiceInfinispanWithAutoscale(InfinispanOperatorProvisionerTest.java:389)
...
```

> Do you have some tracker for the last part of #190 ?
Thanks, just logged: https://github.com/Intersmash/intersmash/issues/195

> > Another issue should then track the effort to update the Intersmash provisioning tooling for Infinispan provisioning to the latest version, and check whether this would work with against product bits.

> Generally I'm not sure whether this is upstream related only, or whether [this](https://infinispan.org/docs/infinispan-operator/main/operator.html#services_services) is related with product as well.

Not yet related with productized version, tests that use `.spec.service.type=cache` are still passing with the latest Red Hat Data Grid Operator version (8.5.2), which installs Red Hat Data Grid Server 8.5.0.GA, i.e. `.spec.service.type=cache` is still supported.
But this doesn't change a thing, as users can still leverage the spec, since CRDs still allow to do so. 
We need to remove the test, though, since Intersmash is following a comunity-first approach.

**Comment by marekkopecky** [comment]
@fabiobrz Thank you for the explanation! Based on it, MR LGTM. Merging.

**Pull request merged**
