### PR TITLE
[issue 136] - Adding a specific e2e script for the OpenShift CI periodic prow job (and minor fixes/cleanup)

### LINKED ISSUE #136: The OpenShift CI e2e periodic Prow job is failing
**Describe the bug** 
The OpenShift CI e2e periodic Prow job is failing, see e.g.: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-Intersmash-intersmash-main-periodic-intersmash-e2e-periodic/1751183301877436416 

**To Reproduce**
See the link above

**Expected behavior**
The CI script should run as planned withough errors, in order to report test results periodically and keep the provisioning logic under control with supported services/products

**Screenshots**
See the link above

**Additional context**
It is failing because after [the](https://github.com/Intersmash/intersmash/pull/129) the e2e scripts expect environment variables which are only valid for presubmit (i.e. PR validation) jobs. We need a specific script that would not use such variables for the periodic job.

### PR DESCRIPTION
**Pull request by fabiobrz**
## Description

Fix #136 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - [ ] I have implemented unit tests to cover my changes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by fabiobrz** [comment]
Once https://github.com/openshift/release/pull/48388 is merged and CI checks are green here, we can merge this safely.

**Review by tommaso-borgato — APPROVED** [review]
LGTM: basically the periodic job doesn't use PR author because there is no PR in periodic job....

**Pull request merged**
