### PR TITLE
Add application descriptor documentation to README

### PR DESCRIPTION
**Pull request by fabiobrz**
## Description
Adding the Application descriptor building block documentation to the main README file 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - [x] I have implemented unit tests to cover my changes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by fabiobrz** [comment]
Hi @rsearls - do we need anything else here?

**Comment by rsearls** [comment]
I don't think so.

**Comment by fabiobrz** [comment]
Ok thanks, merged!

**Pull request merged**
