### PR TITLE
[issue 134] - Document next milestone goals

### LINKED ISSUE #134: Document IM2 goals and next steps
The main goals of the new milestone (IM2) should be documented in the README, along with other relevant plans for the future.

---
* Environment: docs, README
* Steps to reproduce: N/A

### PR DESCRIPTION
**Pull request by fabiobrz**
## Description
Fix #134 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - [ ] **N/A** - I have implemented unit tests to cover my changes
 - [ ] **N/A** - I tested my code in OpenShift

### CODE REVIEW

**Comment by marekkopecky** [comment]
Are those goals described in github issues (or maybe on jira)? From my PoV, those tasks needs to be described there anyway (maybe with "next_release" label, or something like that) with more details and also can be filtered there by some priorities (eg based on "high_prio" / "low_prio" labels, or something like that), so maybe that it's duplication of content to maintain tasks in readme as well?

**Comment by fabiobrz** [comment]
> Are those goals described in github issues (or maybe on jira)? From my PoV, those tasks needs to be described there anyway (maybe with "next_release" label, or something like that) with more details and also can be filtered there by some priorities (eg based on "high_prio" / "low_prio" labels, or something like that), so maybe that it's duplication of content to maintain tasks in readme as well?

Thanks @marekkopecky - Maybe I am getting it wrong but the text that this PR is adding contains the link to the relevant milestone. Isn't that enough? Or am I missing the point?
Re the location for the issues, some time ago we agreed that we can have a single JIRA tracker for each milestone, since we prefer to have issues described in GitHub ATM.

**Comment by marekkopecky** [comment]
> Maybe I am getting it wrong but the text that this PR is adding contains the link to the relevant milestone. Isn't that enough?

> Re the location for the issues, some time ago we agreed that we can have a single JIRA tracker for each milestone, since we prefer to have issues described in GitHub ATM.

Ah, good point, the link for github issues is there, +1, one jira is ok as well. But priorities are not defined in github list and some tasks from this MR is not there at all (eg I don't see an issues for Quarkus or logo). So if someone want to see upcoming tasks, they needs to check readme (this MR) and https://github.com/Intersmash/intersmash/milestone/2, and still don't see the priorities there. To be realistic, I guess that not all of mentioned tasks will be done in next milestone, so priorities could help here.

> That being said, this text in the README is just about a subset, mentioned just as an advertisement.

Well, I would just prefer to keep link to github and maybe add some explanations of labels here in readme. But remove the details, those are duplicated here from the list on github ( https://github.com/Intersmash/intersmash/milestone/2 ). It would simplify the future maintenance. Anyway, I don't have strong feeling here. If you reconsider it and still think that this advertisement is worth the extra maintenance, we can keep subset of tasks here.

**Comment by fabiobrz** [comment]
> > Maybe I am getting it wrong but the text that this PR is adding contains the link to the relevant milestone. Isn't that enough?
> 
> > Re the location for the issues, some time ago we agreed that we can have a single JIRA tracker for each milestone, since we prefer to have issues described in GitHub ATM.
> 
> Ah, good point, the link for github issues is there, +1, one jira is ok as well. But priorities are not defined in github list and some tasks from this MR is not there at all (eg I don't see an issues for Quarkus or logo). So if someone want to see upcoming tasks, they needs to check readme (this MR) and https://github.com/Intersmash/intersmash/milestone/2, and still don't see the priorities there. To be realistic, I guess that not all of mentioned tasks will be done in next milestone, so priorities could help here.

I agree with you about priority, and also about missing GitHub issues for items in the list. 
We're still defining it, though, that is why the milestone is still being mentioned as WIP.
So yes, I'd say the next action item for this should be to start a discussion for assigning labels to the milestone issues, although I think this should be done asynchronously and not block this PR from being merged.

> 
> > That being said, this text in the README is just about a subset, mentioned just as an advertisement.
> 
> Well, I would just prefer to keep link to github and maybe add some explanations of labels here in readme. But remove the details, those are duplicated here from the list on github ( https://github.com/Intersmash/intersmash/milestone/2 ). It would simplify the future maintenance. Anyway, I don't have strong feeling here. If you reconsider it and still think that this advertisement is worth the extra maintenance, we can keep subset of tasks here.

I really like the concept of advertising some (hopefully) attractive features, you're right about the maintenance effort though, so I'll keep it to one liner, and link the milestone.

**Comment by marekkopecky** [comment]
+1, thank you! I'm going to merge this PR once github allows it to me (probably after CI runs).

**Pull request merged**
