### PR TITLE
[issue 80] - Adding EAP 7.z template provisioner

### LINKED ISSUE #80: [iisue 80] - Add EAP 7 provisioning tooling
**Is your feature request related to a problem? Please describe.**
Follows up on [https://github.com/Intersmash/intersmash/pull/70](https://github.com/Intersmash/intersmash/pull/70#issuecomment-1651565391) - in the context of using Intersmash with productized bits and deliverables, see https://github.com/Intersmash/intersmash/issues/62

This is mainly needed to use Intersmash for testing the EAP 7 stream.

**Describe the solution you'd like**

- [x] EAP 7 Image provisioner: **Done**, see #98 
- [x] EAP 7 Template based provisioner: **Done**, see  #104 
- [x] EAP 7 s2i Build provisioner - **Done**, see #106

**Describe alternatives you've considered**
Rework internal tests that are currently using EAP image and template based provisioners in order to use different ones but that would require for more work and time.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by fabiobrz**
## Description
Part of #80 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - [x] I have implemented unit tests to cover my changes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Review by Tommy74 — APPROVED** [review]

**Review by tommaso-borgato — COMMENTED** [review]
@fabiobrz  I reviewed the changes and I just have one question: where can I see that test Eap7TemplateProvisionerTestCase is passing?

**Comment by fabiobrz** [comment]
> @fabiobrz I reviewed the changes and I just have one question: where can I see that test Eap7TemplateProvisionerTestCase is passing?

It is visible in the productised variant of the [e2e tests logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/Intersmash_intersmash/104/pull-ci-Intersmash-intersmash-main-prod-intersmash-e2e-prod/1720008519010226176/artifacts/intersmash-e2e-prod/intersmash-prod-build/build-log.txt).

**Pull request merged**
