### PR TITLE
[issue 193] - Fix the KafkaOperatorprovisionerTest

### LINKED ISSUE #193: Kafka Operator tests are failing when using community deliverables
Kafka Operator tests are failing when using community deliverables:

```
...
[2024-08-31 15:08:07,092] INFO - *** KafkaOperatorProvisionerTest#basicProvisioningTest() is starting ***
[2024-08-31 15:08:07,312] INFO - Waiting up to 20 seconds. Reason: Waiting for the project to be created.
[2024-08-31 15:08:07,636] INFO - Subscribing the strimzi-kafka-operator operator
[2024-08-31 15:18:55,124] ERROR- Waiting for the Kafka cluster instance ended with a timeout. Here is the list of instance conditions found there:
[2024-08-31 15:18:55,130] ERROR-     |- NotReady:True:Unsupported Kafka.spec.kafka.version: 3.6.0. Supported versions are: [3.7.0, 3.7.1, 3.8.0]
[2024-08-31 15:18:55,131] ERROR-     |- Warning:True:In resource Kafka(appsint-tpbr/kafka-test) in API version kafka.strimzi.io/v1beta2 the reconciliationIntervalSeconds property at path spec.entityOperator.topicOperator.reconciliationIntervalSeconds has been deprecated, and should now be configured using .spec.entityOperator.topicOperator.reconciliationIntervalMs.
[2024-08-31 15:18:55,189] INFO - *** KafkaOperatorProvisionerTest#basicProvisioningTest() failed after 0:10:48.096. ***
...
```

From the logs it looks like the Kafka supported version must be updated to the latest in [KafkaOperatorApplication](https://github.com/Intersmash/intersmash/blob/main/provisioners/src/main/java/org/jboss/intersmash/application/openshift/KafkaOperatorApplication.java#L36). An alternative option is to provide a different value (e.g.: `strimzi-0.42.x`) via `intersmash.kafka.operators.channel` in order to let Intersmash install a previous version of the Kafka Operator.

* Environment: testsuite/integration-tests, KefakaOperatorProvisionerTest, when executed with commuity images and deliverables
* Steps to reproduce: 
1. `mvn clean install --batch-mode -DskipTests`
2. `mvn test -pl testsuite/integration-tests -Dtest=KafkaOperatorProvisionerTest`

### PR DESCRIPTION
**Pull request by fabiobrz**
# Description
Fix the KafkaOperatorprovisionerTest in order to support the latest Kafka version, i.e. 3.8.0. Updating documentation accordingly

Closes #193 

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - [x] I have implemented unit tests to cover my changes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by fabiobrz** [comment]
Intersmash PR CI check results
---
Hi @fabiobrz, this comment is meant to report the outcome of Intersmash integration tests,
which were triggered by @fabiobrz comment, see https://github.com/Intersmash/intersmash/pull/194#issuecomment-2324017261.

CI checks job <*continuous-testing-umb-listener-for-intersmash-pr-checks#92*> **FAILED**:


- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-community#39*> reported failures.

- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-products-jboss-eap#51*> reported failures.

- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-products-jboss-eap-xp#57*> reported failures.

    Please verify your changes locally or reach out to maintainers in order to investigate the issues.

**Comment by fabiobrz** [comment]
Intersmash PR CI check results
---
Hi @fabiobrz, this comment is meant to report the outcome of Intersmash integration tests,
which were triggered by @fabiobrz comment, see https://github.com/Intersmash/intersmash/pull/194#issuecomment-2324080062.

CI checks job <*continuous-testing-umb-listener-for-intersmash-pr-checks#94*> **FAILED**:


- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-community#40*> reported failures.

- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-products-jboss-eap#52*> reported failures.

- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-products-jboss-eap-xp#58*> reported failures.

    Please verify your changes locally or reach out to maintainers in order to investigate the issues.

**Comment by fabiobrz** [comment]
Intersmash PR CI check results
---
Hi @fabiobrz, this comment is meant to report the outcome of Intersmash integration tests,
which were triggered by @fabiobrz comment, see https://github.com/Intersmash/intersmash/pull/194#issuecomment-2324080062.

CI checks job <*continuous-testing-umb-listener-for-intersmash-pr-checks#96*> **FAILED**:


- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-community#42*> reported failures.

- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-products-jboss-eap#53*> reported failures.

- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-products-jboss-eap-xp#59*> reported failures.

    Please verify your changes locally or reach out to maintainers in order to investigate the issues.

**Comment by fabiobrz** [comment]
Intersmash PR CI check results
---
Hi @fabiobrz, this comment is meant to report the outcome of Intersmash integration tests,
which were triggered by @fabiobrz comment, see https://github.com/Intersmash/intersmash/pull/194#issuecomment-2325724890.

CI checks job <*continuous-testing-umb-listener-for-intersmash-pr-checks#101*> **FAILED**:


- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-community#46*> reported failures.

- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-products-jboss-eap#57*> reported failures.

- Intersmash integration tests job <*eap-8.x-intersmash-integration-tests-products-jboss-eap-xp#63*> reported failures.

    Please verify your changes locally or reach out to maintainers in order to investigate the issues.

**Comment by marekkopecky** [comment]
Thank you for this MR, LGTM, merging.

**Pull request merged**
